basePath: /
definitions:
  api.Employee:
    properties:
      age:
        type: integer
      dept:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for managing employees.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Employee API
  version: "1.0"
paths:
  /employees:
    get:
      consumes:
      - application/json
      description: Get all employees
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Employee'
            type: array
      summary: Get all employees
      tags:
      - employees
    post:
      consumes:
      - application/json
      description: Create a new employee
      parameters:
      - description: Employee
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/api.Employee'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Employee'
      summary: Create a new employee
      tags:
      - employees
  /employees/{id}:
    get:
      consumes:
      - application/json
      description: Get an employee by ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Employee'
        "404":
          description: Employee not found
          schema:
            type: string
      summary: Get an employee by ID
      tags:
      - employees
    put:
      consumes:
      - application/json
      description: Update an employee
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      - description: Employee
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/api.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Employee'
        "404":
          description: Employee not found
          schema:
            type: string
      summary: Update an employee
      tags:
      - employees
swagger: "2.0"
